default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: open_pv_market_mapper_development

test:
  <<: *default
  database: open_pv_market_mapper_test

production:
  <<: *default
  database: open_pv_market_mapper_production
  username: open_pv_market_mapper
  password: <%= ENV['OPEN_PV_MARKET_MAPPER_DATABASE_PASSWORD'] %>
